<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="fer">

  <xacro:include filename="$(find franka_description)/robots/common/utils.xacro" />

  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <!-- arm_id: Namespace of the robot arm. Serves to differentiate between arms in case of multiple instances. -->
  <!-- joint_limits: description of the joint limits that comes from a YAML file. Example definition: ${xacro.load_yaml('$(find franka_description)/robots/fr3/joint_limits.yaml')} -->
  <!-- kinematics: description of the kinematics that comes from a YAML file. Example definition: ${xacro.load_yaml('$(find franka_description)/robots/fr3/kinematics.yaml')} -->
  <!-- inertials: description of the inertials that comes from a YAML file. Example definition: ${xacro.load_yaml('$(find franka_description)/robots/fr3/inertials.yaml')} -->
  <!-- dynamics: description of the dynamics that comes from a YAML file. Example definition: ${xacro.load_yaml('$(find franka_description)/robots/fr3/dynamics.yaml')} -->

  <xacro:macro name="franka_arm" params="arm_id description_pkg:='franka_description' connected_to:='base' xyz:='0 0 0' rpy:='0 0 0' gazebo:='false' safety_distance:=0 joint_limits inertials kinematics dynamics with_sc:=false" >
    <xacro:if value="${gazebo}">
      <xacro:property name="connected_to" value="" />
    </xacro:if>

    <xacro:unless value="${not connected_to}">
      <link name="${connected_to}">
      </link>
      <joint name="${connected_to}_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${arm_id}_link0"/>
        <origin rpy="${rpy}" xyz="${xyz}"/>
      </joint>
    </xacro:unless>

    <xacro:link_with_sc name="link0" gazebo="${gazebo}" with_sc="${with_sc}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="-0.075 0 0.06" direction="x" radius="${0.06+safety_distance}" length="0.03" />
      </self_collision_geometries>
    </xacro:link_with_sc>

    <xacro:link_with_sc name="link1" gazebo="${gazebo}" with_sc="${with_sc}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="0 0 -191.5e-3" radius="${0.06+safety_distance}" length="0.283" />
      </self_collision_geometries>
    </xacro:link_with_sc>

    <joint name="${arm_id}_joint1" type="revolute">
      <xacro:franka-kinematics name="joint1" config="${kinematics}" />
      <parent link="${arm_id}_link0" />
      <child link="${arm_id}_link1" />
      <axis xyz="0 0 1" />
      <xacro:franka-limits name="joint1" config="${joint_limits}" />
      <xacro:franka-dynamics name="joint1" config="${dynamics}" />
    </joint>

    <xacro:link_with_sc name="link2" gazebo="${gazebo}" with_sc="${with_sc}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="0 0 0" radius="${0.06+safety_distance}" length="0.12" />
      </self_collision_geometries>
    </xacro:link_with_sc>

    <joint name="${arm_id}_joint2" type="revolute">
      <xacro:franka-kinematics name="joint2" config="${kinematics}" />
      <parent link="${arm_id}_link1" />
      <child link="${arm_id}_link2" />
      <axis xyz="0 0 1" />
      <xacro:franka-limits name="joint2" config="${joint_limits}" />
      <xacro:franka-dynamics name="joint2" config="${dynamics}" />
    </joint>

    <xacro:link_with_sc name="link3" gazebo="${gazebo}" with_sc="${with_sc}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="0 0 -0.145" radius="${0.06+safety_distance}" length="0.15" />
      </self_collision_geometries>
    </xacro:link_with_sc>

    <joint name="${arm_id}_joint3" type="revolute">
      <xacro:franka-kinematics name="joint3" config="${kinematics}" />
      <parent link="${arm_id}_link2" />
      <child link="${arm_id}_link3" />
      <axis xyz="0 0 1" />
      <xacro:franka-limits name="joint3" config="${joint_limits}" />
      <xacro:franka-dynamics name="joint3" config="${dynamics}" />
    </joint>

    <xacro:link_with_sc name="link4" gazebo="${gazebo}" with_sc="${with_sc}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="0 0 0" radius="${0.06+safety_distance}" length="0.12" />
     </self_collision_geometries>
    </xacro:link_with_sc>

    <joint name="${arm_id}_joint4" type="revolute">
      <xacro:franka-kinematics name="joint4" config="${kinematics}" />
      <parent link="${arm_id}_link3" />
      <child link="${arm_id}_link4" />
      <axis xyz="0 0 1" />
      <xacro:franka-limits name="joint4" config="${joint_limits}" />
      <xacro:franka-dynamics name="joint4" config="${dynamics}" />
    </joint>

    <xacro:link_with_sc name="link5" gazebo="${gazebo}" with_sc="${with_sc}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="0 0 -0.26"    radius="${0.060+safety_distance}" length="0.10" />
        <xacro:collision_capsule xyz="0 0.08 -0.13" radius="${0.025+safety_distance}" length="0.14" />
      </self_collision_geometries>
    </xacro:link_with_sc>

    <joint name="${arm_id}_joint5" type="revolute">
      <xacro:franka-kinematics name="joint5" config="${kinematics}" />
      <parent link="${arm_id}_link4" />
      <child link="${arm_id}_link5" />
      <axis xyz="0 0 1" />
      <xacro:franka-limits name="joint5" config="${joint_limits}" />
      <xacro:franka-dynamics name="joint5" config="${dynamics}" />
    </joint>

    <xacro:link_with_sc name="link6" gazebo="${gazebo}" with_sc="${with_sc}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="0 0 -0.03" radius="${0.05+safety_distance}" length="0.08" />
      </self_collision_geometries>
    </xacro:link_with_sc>

    <joint name="${arm_id}_joint6" type="revolute">
      <xacro:franka-kinematics name="joint6" config="${kinematics}" />
      <parent link="${arm_id}_link5" />
      <child link="${arm_id}_link6" />
      <axis xyz="0 0 1" />
      <xacro:franka-limits name="joint6" config="${joint_limits}" />
      <xacro:franka-dynamics name="joint6" config="${dynamics}" />
    </joint>

    <xacro:link_with_sc name="link7" gazebo="${gazebo}" rpy="0 0 ${pi/4}" with_sc="${with_sc}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="0 0 0.01" direction="z" radius="${0.04+safety_distance}" length="0.14" />
        <xacro:collision_capsule xyz="0.06 0 0.082" direction="x" radius="${0.03+safety_distance}"  length="0.01" />
      </self_collision_geometries>
    </xacro:link_with_sc>

    <joint name="${arm_id}_joint7" type="revolute">
      <xacro:franka-kinematics name="joint7" config="${kinematics}" />
      <parent link="${arm_id}_link6"/>
      <child link="${arm_id}_link7"/>
      <axis xyz="0 0 1"/>
      <xacro:franka-limits name="joint7" config="${joint_limits}" />
      <xacro:franka-dynamics name="joint7" config="${dynamics}" />
    </joint>

    <link name="${arm_id}_link8"/>

    <joint name="${arm_id}_joint8" type="fixed">
      <xacro:franka-kinematics name="joint8" config="${kinematics}" />
      <parent link="${arm_id}_link7" />
      <child link="${arm_id}_link8" />
    </joint>
    
    <!-- Unscrewer tool link -->
    <link name="unscrewer">
      <visual>
        <geometry>
          <mesh filename="package://franka_description/meshes/robot_arms/fr3/visual/unscrewer.dae" scale="1 1 1"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0.0"/>  
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.01575" length="0.1048"/>
        </geometry>
        <origin xyz="0 0 -0.0524" rpy="0 0 0"/>
      </collision>
      <collision>
        <geometry>
          <cylinder radius="0.0385" length="0.085"/>
        </geometry>
        <origin xyz="0 0 -0.1473" rpy="0 0 0"/> 
      </collision>
      <inertial>
        <mass value="0.264659"/> 
        <origin xyz="-0.00000023 0.0000002276 -0.09747" rpy="0 0 0"/> 
        <inertia ixx="0.000461783" ixy="0" ixz="0" iyy="0.000446552" iyz="-0.000000005" izz="0.000047542"/>
      </inertial>
    </link>
    
    <joint name="unscrewer_joint" type="fixed">
      <xacro:franka-kinematics name="joint_unscrewer" config="${kinematics}" />
      <parent link="${arm_id}_link8"/>
      <child link="unscrewer"/>
    </joint>

    <link name="camera">
      <visual>
        <geometry>
          <mesh filename="package://franka_description/meshes/robot_arms/fr3/visual/camera.dae" scale="1 1 1"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.027" length="0.20993"/>
        </geometry>
        <origin xyz="0 0 -0.104965" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.178"/> 
        <origin xyz="-0.005423 0.000141 -0.097517" rpy="0 0 0"/> 
        <inertia ixx="0.000934085" ixy="0.000000103" ixz="-0.000064273" iyy="0.000938346" iyz="0.000001638" izz="0.000037901"/>
      </inertial>
    </link>
    
    <joint name="camera_joint" type="fixed">
      <xacro:franka-kinematics name="joint_camera" config="${kinematics}" />
      <parent link="${arm_id}_link8"/>
      <child link="camera"/>
    </joint>

  </xacro:macro>
</robot>